import nltk
nltk.download('vader_lexicon')
nltk.download('averaged_perceptron_tagger')
nltk.download('punkt_tab')
nltk.download('maxent_ne_chunker')
nltk.download('words')
nltk.download('punkt')
# nltk.download('averaged_perceptron_tagger')
nltk.download('stopwords')
nltk.download('perluniprops')
nltk.download('nonbreaking_prefixes')
nltk.download('wordnet')
nltk.download('snowball_data')